# Assignment.08 - Program 01

## Packages

In [64]:
import pandas as pd
import seaborn as sns

## Tasks

In [65]:
# 1 Read the data from the CSV file into a DataFrame and display the data to get a count of the number of rows.
data = pd.read_csv("ramen-ratings.csv")
data

,Review #,Brand,Variety,Style,Country,Stars,Top Ten
0,2580,New Touch,T's Restaurant Tantanmen,Cup,Japan,3.75,NaN
1,2579,Just Way,Noodles Spicy Hot Sesame Spicy Hot Sesame Guan...,Pack,Taiwan,1,NaN
2,2578,Nissin,Cup Noodles Chicken Vegetable,Cup,USA,2.25,NaN
3,2577,Wei Lih,GGE Ramen Snack Tomato Flavor,Pack,Taiwan,2.75,NaN
4,2576,Ching's Secret,Singapore Curry,Pack,India,3.75,NaN
...,...,...,...,...,...,...,...
2575,5,Vifon,"Hu Tiu Nam Vang [""Phnom Penh"" style] Asian Sty...",Bowl,Vietnam,3.5,NaN
2576,4,Wai Wai,Oriental Style Instant Noodles,Pack,Thailand,1,NaN
2577,3,Wai Wai,Tom Yum Shrimp,Pack,Thailand,2,NaN
2578,2,Wai Wai,Tom Yum Chili Flavor,Pack,Thailand,2,NaN
2579,1,Westbrae,Miso Ramen,Pack,USA,0.5,NaN

In [66]:
# 2 Rename the Stars column to Rating.
data = data.rename(columns={'Stars': 'Rating'})

In [67]:
# 3 Convert the Style column to the category type.
data['Style'] = data['Style'].astype(dtype='category')
data.dtypes

Review #       int64
Brand         object
Variety       object
Style       category
Country       object
Rating        object
Top Ten       object
dtype: object

In [68]:
# 4 Drop the country column
data = data.drop('Country', axis=1)

In [69]:
# 5 Check that the changes were applied to the DataFrame
data.head()

,Review #,Brand,Variety,Style,Rating,Top Ten
0,2580,New Touch,T's Restaurant Tantanmen,Cup,3.75,NaN
1,2579,Just Way,Noodles Spicy Hot Sesame Spicy Hot Sesame Guan...,Pack,1,NaN
2,2578,Nissin,Cup Noodles Chicken Vegetable,Cup,2.25,NaN
3,2577,Wei Lih,GGE Ramen Snack Tomato Flavor,Pack,2.75,NaN
4,2576,Ching's Secret,Singapore Curry,Pack,3.75,NaN

In [70]:
# 6 Rename the Brand column to Company and the Variety column to Product.
data = data.rename(columns={'Brand': 'Company'})
data = data.rename(columns={'Variety': 'Product'})

In [71]:
# 7 Use the duplicated() method to display all rows with duplicate Company/Product combinations
data[data.duplicated(['Company', 'Product'], keep=False)]

,Review #,Company,Product,Style,Rating,Top Ten
2,2578,Nissin,Cup Noodles Chicken Vegetable,Cup,2.25,NaN
24,2556,Ching's Secret,Hot Garlic Instant Noodles,Pack,4.25,NaN
47,2533,Nongshim,Shin Ramyun Black,Pack,5,NaN
70,2510,MyKuali,Penang Red Tom Yum Goong Noodle,Pack,5,NaN
76,2504,Nongshim,Shin Ramyun,Pack,3,NaN
...,...,...,...,...,...,...
2548,32,Koka,Mi Hai Cua Crab Flavor,Pack,3.5,NaN
2555,25,Nissin,Demae Ramen Spicy Flavor,Pack,3,NaN
2559,21,Nongshim,Champong Oriental Noodles,Pack,4,NaN
2561,19,Nongshim,Shin Ramyun,Pack,4,NaN
2568,12,Sapporo Ichiban,Shrimp Flavor,Pack,2.5,NaN

In [72]:
# 8 Drop all rows with duplicate Company/Product combinations except for the first row in each set. 
# Then, display the data to get a count of the number of rows, and compare that with the original number of rows to see how many were dropped.
data = data.drop_duplicates(['Company', 'Product'], keep='first')

#2580 rows original - 2520 rows after drop = 60 rows dropped

In [73]:
# 9 Drop any rows that have missing values.
data = data.dropna()

In [74]:
# 10 Check again to make sure that all of your changes were applied.
data

,Review #,Company,Product,Style,Rating,Top Ten
616,1964,MAMA,Instant Noodles Coconut Milk Flavour,Pack,5,2016 #10
633,1947,Prima Taste,Singapore Laksa Wholegrain La Mian,Pack,5,2016 #1
655,1925,Prima,Juzz's Mee Creamy Chicken Flavour,Pack,5,2016 #8
673,1907,Prima Taste,Singapore Curry Wholegrain La Mian,Pack,5,2016 #5
752,1828,Tseng Noodles,Scallion With Sichuan Pepper Flavor,Pack,5,2016 #9
891,1689,Wugudaochang,Tomato Beef Brisket Flavor Purple Potato Noodle,Pack,5,2016 #7
942,1638,A-Sha Dry Noodle,Veggie Noodle Tomato Noodle With Vine Ripened ...,Pack,5,2015 #10
963,1617,MyKuali,Penang Hokkien Prawn Noodle (New Improved Taste),Pack,5,2015 #7
995,1585,CarJEN,Nyonya Curry Laksa,Pack,5,2015 #4
1059,1521,Maruchan,Gotsumori Sauce Yakisoba,Tray,5,2015 #9
1072,1508,Mamee,Chef Gold Recipe Mi Kari Seribu Rasa,Pack,5,2015 #6
1109,1471,Mama,Instant Noodles Shrimp Creamy Tom Yum Flavour ...,Pack,5,2013 #10
1114,1466,Mama,Oriental Style Instant Noodles Green Curry Fla...,Pack,5,2015 #8
1250,1330,Sapporo Ichiban,Otafuku Okonomi Sauce Yakisoba,Tray,5,2014 #4
1278,1302,Mama,Instant Noodles Yentafo Tom Yum Mohfai Flavour,Pack,5,2014 #10
1309,1271,Prima Taste,Singapore Chilli Crab La Mian,Pack,5,2014 #8
1382,1198,Samyang Foods,Maesaengyitangmyun Baked Noodle,Pack,5,2014 #5
1397,1183,Paldo,Cheese Noodle,Pack,5,2014 #6
1493,1087,MyKuali,Penang White Curry Noodle,Pack,5,2014 #1
1588,992,Prima Taste,Singapore Laksa La Mian,Pack,5,2013 #1
1589,991,Prima Taste,Singapore Curry La Mian,Pack,5,2013 #2
1646,934,Nongshim,Jinjja Jinjja Flamin' Hot & Nutty,Pack,5,2013 #4
1670,910,Paldo,Namja Ramyun,Bowl,4.25,\n
1846,734,Indomie,Mi Goreng Rasa Ayam Panggang Jumbo (Local),Pack,5,\n
1865,715,Indomie,Mi Goreng Rendang (Import),Pack,5,2013 #3
1972,608,Koka,Spicy Black Pepper,Pack,5,2012 #10
2146,434,Mi Sedaap,Kari Spesial,Pack,4.5,2012 #5
2188,392,Nissin,Yakisoba Noodles Karashi,Tray,5,2012 #3
2189,391,Myojo,Hyoubanya No Chukasoba Oriental,Pack,4.25,2012 #6
2248,332,Nongshim,Champong Oriental Noodles,Cup,3.75,\n
2295,285,Doll,Artificial Chicken,Pack,4.5,2012 #9
2475,105,Indomie,Special Fried Curly Noodle,Pack,5,2012 #1
2533,47,Indomie,Mi Goreng Jumbo Barbecue Chicken,Pack,5,2012 #2
2535,45,Indomie,Mi Goreng Sate,Pack,5,\n
2549,31,Myojo,Ippeichan Yakisoba,Tray,4,2013 #6
2567,13,Sapporo Ichiban,Chow Mein,Pack,5,2012 #4